version: '3'
services:
  javascript-code-runner-01:
    container_name: doatask_javascript_code_runner_01
    build:
      context: ./
      dockerfile: ./docker/code-plugin/Dockerfile-JavaScript
    ports:
      - "10000:10000"
    restart: unless-stopped
    environment:
      language: JavaScript
  javascript-code-runner-02:
    container_name: doatask_javascript_code_runner_02
    build:
      context: ./
      dockerfile: ./docker/code-plugin/Dockerfile-JavaScript
    ports:
      - "10002:10000"
    restart: unless-stopped
    environment:
      language: JavaScript
  python-code-runner-01:
    container_name: doatask_python_code_runner_01
    build:
      context: ./
      dockerfile: ./docker/code-plugin/Dockerfile-Python
    ports:
      - "10001:10001"
    restart: unless-stopped
    environment:
      language: Python
  python-code-runner-02:
    container_name: doatask_python_code_runner_02
    build:
      context: ./
      dockerfile: ./docker/code-plugin/Dockerfile-Python
    ports:
      - "10003:10001"
    restart: unless-stopped
    environment:
      language: Python
  java-code-runner-01:
    container_name: doatask_java_code_runner_01
    build:
      context: ./
      dockerfile: ./docker/code-plugin/Dockerfile-Java
    ports:
      - "10004:10002"
    restart: unless-stopped
    environment:
      language: Java
  java-code-runner-02:
    container_name: doatask_java_code_runner_02
    build:
      context: ./
      dockerfile: ./docker/code-plugin/Dockerfile-Java
    ports:
      - "10005:10002"
    restart: unless-stopped
    environment:
      language: Java
