# creates PostgreSQL database image and pgadmin4 image and Nest server image

version: '3'
services:
  postgres:
    build:
      context: ./
      dockerfile:  ./docker/postgres/Dockerfile
    hostname: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped

  server:
    build:
      context: ./
      dockerfile:  ./docker/nest/Dockerfile
    depends_on:
      - postgres
    ports:
      - ${NEST_PORT}:${NEST_PORT}

volumes:
  pg-data: